#!/bin/bash

##############################################################
#		Alias Listing w/ Comments		     #
#		Nicholas Schmidt			     #
#		09 Dec 2013				     #
#							     #
#	Verifies that a .alias or /etc/alias file exists,    #
#	Then proceeds to out it w/ comments on a separate    #
#	column.						     #
##############################################################


# Print all lines w/ alias && the comment field redacted.
function alias-read() {
	if [ -n $1 -a -r $1 ]
		then
			awk '{ $1=""; $3=""; print $0}' $1
	fi
}


#incl file checking! useful user feedback!!
if [ ! -r ~/.alias ]
	then
		printf "~/.alias file not found!\n"
fi

if [ ! -x ~/.alias ]
	then
		printf "~/.alias file cannot be executed!\n"
fi
 
if [ ! -r /etc/alias ]
	then
		printf "/etc/alias file not found!\n"
fi

if [ ! -x /etc/alias ]
	then
		printf "/etc/alias file cannot be executed!\n"
fi

if [ -r ~/.alias ]
	then
		alias-read "~/.alias"
fi

if [ -r /etc/alias ]
	then
		alias-read "/etc/alias"
fi
